# Generated by Django 3.0.6 on 2020-06-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200518_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(default='blog/post_detail.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
