# Generated by Django 3.0.6 on 2020-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Менюшки'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Для зарегистрированных?'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='is_auth',
            field=models.BooleanField(default=True, verbose_name='Для зарегистрированных?'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='status',
            field=models.BooleanField(default=True, verbose_name='вкл'),
        ),
    ]
