# Generated by Django 3.0.6 on 2020-06-09 12:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('menu', '0002_auto_20200607_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='active',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='is_auth',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='active',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='is_auth',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Ссылка на'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='object_id',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='ID записи'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='anchor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Якорь'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.MenuItems', verbose_name='Родительское пункт'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Только для зарегистрированных'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название пункта меню на сайте'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url на внешний ресурс'),
        ),
    ]
